In [217]:
'''

CINEMAC. 

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

project for the course of Network Analysis - 2022/2023
Realized by.
	Andrea D'Arpa
	Maddalena Ghiotto		
	Chloe Papadopoulou

'''
import os
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from ast import literal_eval
from listReader import *


# creating the tables with pandas to interact with our datasets
# getting the current working directory
cwd = os.getcwd()

# name = cwd+'/datasets/name.basics.tsv'
# name_table = pd.read_csv(name , sep='\t', header=0)

# title = cwd+'/datasets/title.principals.tsv'
# title_table = pd.read_csv(title , sep='\t', header=0)

# #import titles ds to match the movie-links titles, 
# title_name = cwd+'/datasets/title.basics.tsv'
# title_name_table= pd.read_csv(title_name, sep='\t', header=0, low_memory=False)

                              
# # dtype={'tconst':'int64',	'titleType':'str',	'primaryTitle':'str',	'originalTitle':'str',	'isAdult':'bool',	'startYear':'int64',	'endYear':'int64',	'runtimeMinutes':'int64',	'genres':'str'})


# countries = cwd+'/datasets/countries.list.gz'
# countries_table = get_movie_countries(countries)
# countries_table.to_csv("countries_table.csv")

movies = cwd+'/datasets/movie-links.list.gz'
movies_table = get_movie_links(movies)
movies_table.to_csv("movies_table.csv")

'''
testing the tables
'''
# print(movies_table.head(5))
# print(countries_table.head(5))
# print(title_table.head(5))
# print(name_table.head(5))


#merge to include countries:

# movies_cit_countries = pd.merge(movies_table, countries_table, on='movie', how='left')

# movies_cit_countries=pd.merge(movies_cit_countries, countries_table, left_on="cites", right_on="movie",how="left")

# movies_cit_countries.rename(columns={"movie_x":"movie","movie_y":"cited_movies","country_x":"movie_country","country_y":"cites_country"},inplace=True)
# movies_cit_countries=movies_cit_countries.reindex(columns= ['movie', 'movie_country', 'cites', 'movie_y','cites_country'])
# movies_cit_countries.drop(columns=['movie_y'], inplace=True)
# movies_cit_countries.head(30)

# str(len(movies_cit_countries)) + " final, original is " + str(len(movies_table))

#the lengths are different and i don't understand why

'\ntesting the tables\n'

In [218]:
#retrieve information for movies collaborators. **not currently working**

#how to match

#append the movie title to the tconst ones.
#split the movie column in the first dataframe to separate title from year
#match both movie title (that is ***included*** in the imdb, so not an exact match) and year with startYear

#replace /n for nan values
title_name_table = title_name_table.replace("\\N", np.nan)


# movies_cit_countries[['title','year']] = movies_cit_countries.movie.str.split("\(", 1, expand=True)
# movies_cit_countries['year']=movies_cit_countries['year'].str.replace(')','')  

# movies_cit_countries[['primaryTitle_citation','year_citation']] = movies_cit_countries.cites.str.split("\(", 1, expand=True)
# movies_cit_countries['year_citation']=movies_cit_countries['year_citation'].str.replace(')','')  


# Define a regular expression pattern to extract the title and year
pattern = r'^(.*) \((\d{4})\)$'

# Apply the pattern to the "movie" column and extract the title and year into separate columns
movies_cit_countries[['title', 'year']] = movies_cit_countries['movie'].str.extract(pattern)
movies_cit_countries[['primaryTitle_citation', 'year_citation']] = movies_cit_countries['cites'].str.extract(pattern)

# Print the first 10 rows of the resulting dataframe to check the output
print(movies_cit_countries.head(100))

non_valid_year = list([y for y in movies_cit_countries['year_citation'].unique() if not (str(y).isdigit() and len(str(y)) == 4)])
non_valid_year

error_rows = movies_cit_countries[movies_cit_countries['year_citation'].isin(non_valid_year)]
error_rows

non_valid_year_x = list([y for y in movies_cit_countries['year_citation'].unique() if not (str(y).isdigit() and len(str(y)) == 4)])
non_valid_year_x

error_rows_x = movies_cit_countries[movies_cit_countries['year_citation'].isin(non_valid_year_x)]
error_rows_x

                                     movie movie_country  \
0                   #DevinAuditions (2016)        Canada
1                   #DevinAuditions (2016)        Canada
2                   #DevinAuditions (2016)        Canada
3                   #DevinAuditions (2016)        Canada
4                   #DevinAuditions (2016)        Canada
..                                     ...           ...
95          'Joe Strummer': The Man (2007)           USA
96    'Kurenai no kenjû' yo eien ni (2000)         Japan
97  'Men Olsenbanden var ikke død!' (1984)        Norway
98  'Men Olsenbanden var ikke død!' (1984)        Norway
99  'Men Olsenbanden var ikke død!' (1984)        Norway

                                             cites cites_country  \
0                                     Alien (1979)            UK
1                                     Alien (1979)           USA
2                                  Die Hard (1988)           USA
3                  Ferris Bueller's Day Off (1986)           USA
4                                Fight Club (1999)           USA
..                                             ...           ...
95    Joe Strummer: The Future Is Unwritten (2007)            UK
96                         Kurenai no kenju (1961)         Japan
97     Olsen-banden møter kongen og knekten (1974)        Norway
98           Olsen-banden og Dynamitt-Harry (1970)        Norway
99  Olsen-banden og Dynamitt-Harry går amok (1973)        Norway

                              title  year  \
0                   #DevinAuditions  2016
1                   #DevinAuditions  2016
2                   #DevinAuditions  2016
3                   #DevinAuditions  2016
4                   #DevinAuditions  2016
..                              ...   ...
95          'Joe Strummer': The Man  2007
96    'Kurenai no kenjû' yo eien ni  2000
97  'Men Olsenbanden var ikke død!'  1984
98  'Men Olsenbanden var ikke død!'  1984
99  'Men Olsenbanden var ikke død!'  1984

                      primaryTitle_citation year_citation
0                                     Alien          1979
1                                     Alien          1979
2                                  Die Hard          1988
3                  Ferris Bueller's Day Off          1986
4                                Fight Club          1999
..                                      ...           ...
95    Joe Strummer: The Future Is Unwritten          2007
96                         Kurenai no kenju          1961
97     Olsen-banden møter kongen og knekten          1974
98           Olsen-banden og Dynamitt-Harry          1970
99  Olsen-banden og Dynamitt-Harry går amok          1973

[100 rows x 8 columns]

Empty DataFrame
Columns: [movie, movie_country, cites, cites_country, title, year, primaryTitle_citation, year_citation]
Index: []

In [219]:
#******TROUBLESHOOTING missing values on merge ********

#encoding is same in both, utf-8 - check
#replaced /n for nan values before

In [220]:
#make sure formats are the same
#assign best datatypes

movies_cit_countries=movies_cit_countries.convert_dtypes()
title_name_table=title_name_table.convert_dtypes()

#they all turn out as str- keeping it for convenience

#remove useless whitespaces
movies_cit_countries['title'] = movies_cit_countries['title'].str.strip()
movies_cit_countries['primaryTitle_citation'] = movies_cit_countries['primaryTitle_citation'].str.strip()

title_name_table['primaryTitle'] = title_name_table['primaryTitle'].str.strip()
title_name_table['originalTitle'] = title_name_table['originalTitle'].str.strip()



#remove duplicates by filtering by type. not very helpful cause it ignores shorts and documentaries but just to check.

title_name_table = title_name_table[title_name_table['titleType'] == 'movie']

title_name_table[title_name_table['primaryTitle'] == 'Fight Club'].values

array([['tt0137523', 'movie', 'Fight Club', 'Fight Club', '0', '1999',
        <NA>, '139', 'Drama']], dtype=object)

In [221]:
#remove duplicates (not ideal for us but just in case)

# movies_cit_countries.drop_duplicates(subset=["primaryTitle_citation", "year_citation"], inplace=True)
# title_name_table.drop_duplicates(subset=["primaryTitle","startYear"], inplace=True)


#check duplicates
# movies_cit_countries['primaryTitle_citation'].duplicated().any()

# title_name_table['primaryTitle'].duplicated().any()


final_df = pd.merge(movies_cit_countries, title_name_table,
             how="left",
             left_on='primaryTitle_citation',
             right_on='originalTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='right', lsuffix='', rsuffix='_citation', sort=False)

                                

final_df

,movie,movie_country,cites,cites_country,title,year,primaryTitle_citation,year_citation,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,#DevinAuditions (2016),Canada,Alien (1979),UK,#DevinAuditions,2016,Alien,1979,tt0078748,movie,Alien,Alien,0,1979,<NA>,117,"Horror,Sci-Fi"
1,#DevinAuditions (2016),Canada,Alien (1979),USA,#DevinAuditions,2016,Alien,1979,tt0078748,movie,Alien,Alien,0,1979,<NA>,117,"Horror,Sci-Fi"
2,#DevinAuditions (2016),Canada,Die Hard (1988),USA,#DevinAuditions,2016,Die Hard,1988,tt0095016,movie,Die Hard,Die Hard,0,1988,<NA>,132,"Action,Thriller"
3,#DevinAuditions (2016),Canada,Die Hard (1988),USA,#DevinAuditions,2016,Die Hard,1988,tt13802348,movie,Die Hard,Die Hard,0,1999,<NA>,<NA>,Action
4,#DevinAuditions (2016),Canada,Ferris Bueller's Day Off (1986),USA,#DevinAuditions,2016,Ferris Bueller's Day Off,1986,tt0091042,movie,Ferris Bueller's Day Off,Ferris Bueller's Day Off,0,1986,<NA>,103,Comedy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564395,è solo questione di punti di vista (2012),Italy,"Un genio, due compari, un pollo (1975)",Italy,è solo questione di punti di vista,2012,"Un genio, due compari, un pollo",1975,tt0073036,movie,"A Genius, Two Partners and a Dupe","Un genio, due compari, un pollo",0,1975,<NA>,126,"Comedy,Western"
564396,è solo questione di punti di vista (2012),Italy,"Un genio, due compari, un pollo (1975)",France,è solo questione di punti di vista,2012,"Un genio, due compari, un pollo",1975,tt0073036,movie,"A Genius, Two Partners and a Dupe","Un genio, due compari, un pollo",0,1975,<NA>,126,"Comedy,Western"
564397,è solo questione di punti di vista (2012),Italy,"Un genio, due compari, un pollo (1975)",West Germany,è solo questione di punti di vista,2012,"Un genio, due compari, un pollo",1975,tt0073036,movie,"A Genius, Two Partners and a Dupe","Un genio, due compari, un pollo",0,1975,<NA>,126,"Comedy,Western"
564398,è solo questione di tempo (2013),Italy,Il successo (1963),Italy,è solo questione di tempo,2013,Il successo,1963,tt0057540,movie,Il successo,Il successo,0,1963,<NA>,104,Comedy
564399,è solo questione di tempo (2013),Italy,Il successo (1963),France,è solo questione di tempo,2013,Il successo,1963,tt0057540,movie,Il successo,Il successo,0,1963,<NA>,104,Comedy

In [222]:
    


null_values = final_df['originalTitle'].isnull() | final_df['originalTitle'].isna()
if null_values.any():
    print(final_df[null_values]['primaryTitle_citation'].unique())
    print(final_df[null_values].values)

<StringArray>
[                          'Love, Simple',
                     'Bud Takes the Cake',
            'Bud and Susie Join the Tecs',
           'Bud and Tommy Take a Day Off',
                   'Down the Mississippi',
                         'Getting Theirs',
                     "Handy Mandy's Goat",
           "Ma's Wipe Your Feet Campaign",
                         'Mice and Money',
                 'Romance and Rheumatism',
 ...
                                 'Dexter',
        'À Saint-Henri le cinq septembre',
                  'Çilgin dersane kampta',
                 'Écono mixte - Volume 1',
                 'Écono mixte - Volume 2',
                          'Une explosion',
 'Épisode de la bataille de Modder-River',
        "Épopée napoléonienne - L'Empire",
                           'Üksindusfilm',
                              'Smáfuglar']
Length: 9505, dtype: string
[['#Rip (2013)' 'USA' 'Love, Simple (2012)' ... <NA> <NA> <NA>]
 ['$10,000 Under a Pillow (1921)' 'USA' 'Bud Takes the Cake (1920)' ...
  <NA> <NA> <NA>]
 ['$10,000 Under a Pillow (1921)' 'USA'
  'Bud and Susie Join the Tecs (1920)' ... <NA> <NA> <NA>]
 ...
 ['Þrestir (2015)' 'Iceland' 'Smáfuglar (2008)' ... <NA> <NA> <NA>]
 ['Þrestir (2015)' 'Denmark' 'Smáfuglar (2008)' ... <NA> <NA> <NA>]
 ['Þrestir (2015)' 'Croatia' 'Smáfuglar (2008)' ... <NA> <NA> <NA>]]

In [223]:
repo_data_ex= movies_cit_countries[movies_cit_countries['primaryTitle_citation'] == 'Fight Club'].values
repo_data_ex

array([['#DevinAuditions (2016)', 'Canada', 'Fight Club (1999)', ...,
        '2016', 'Fight Club', '1999'],
       ['#DevinAuditions (2016)', 'Canada', 'Fight Club (1999)', ...,
        '2016', 'Fight Club', '1999'],
       ['A Matter of Loaf and Death (2008)', 'UK', 'Fight Club (1999)',
        ..., '2008', 'Fight Club', '1999'],
       ...,
       ['Zhara (2006)', 'Russia', 'Fight Club (1999)', ..., '2006',
        'Fight Club', '1999'],
       ['Zombie Nation (2004)', 'USA', 'Fight Club (1999)', ..., '2004',
        'Fight Club', '1999'],
       ['Zombie Nation (2004)', 'USA', 'Fight Club (1999)', ..., '2004',
        'Fight Club', '1999']], dtype=object)

In [224]:


non_valid_year = list([y for y in movies_cit_countries['year'].unique() if not (str(y).isdigit() and len(str(y)) == 4)])
non_valid_year

error_rows = movies_cit_countries[movies_cit_countries['year'].isin(non_valid_year)]
error_rows

Empty DataFrame
Columns: [movie, movie_country, cites, cites_country, title, year, primaryTitle_citation, year_citation]
Index: []

In [225]:
non_valid_year = list([y for y in movies_cit_countries['year_citation'].unique() if not (str(y).isdigit() and len(str(y)) == 4)])
non_valid_year

error_rows = movies_cit_countries[movies_cit_countries['year_citation'].isin(non_valid_year)]
error_rows

Empty DataFrame
Columns: [movie, movie_country, cites, cites_country, title, year, primaryTitle_citation, year_citation]
Index: []

In [226]:
final_df.isnull().sum()

movie                         0
movie_country               534
cites                         0
cites_country                73
title                         0
year                          0
primaryTitle_citation         0
year_citation                 0
tconst                    97565
titleType                 97565
primaryTitle              97565
originalTitle             97565
isAdult                   97565
startYear                152387
endYear                  564400
runtimeMinutes           194488
genres                   116294
dtype: int64

In [228]:
#i tried including all entries (even tv0series), reverted the "regex" pattern, but i always get 109336 null values

In [229]:
%history

'''

CINEMAC.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

project for the course of Network Analysis - 2022/2023
Realized by.
    Andrea D'Arpa
    Maddalena Ghiotto
    Chloe Papadopoulou

'''
import os
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from ast import literal_eval
from listReader import *
!pip install chardet


# creating the tables with pandas to interact with our datasets
# getting the current working directory
cwd = os.getcwd()

name = cwd+'/datasets/name.basics.tsv'
name_table = pd.read_csv(name , sep='\t', header=0)

title = cwd+'/datasets/title.principals.tsv'
title_table = pd.read_csv(title , sep='\t', header=0)

#import titles ds to match the movie-links titles,
title_name = cwd+'/datasets/title.basics.tsv'
title_name_table= pd.read_csv(title_name, sep='\t', header=0, low_memory=False)


# dtype={'tconst':'int64',  'titleType':'str',  'primaryTitle':'str',   'originalTitle':'str',  'isAdult':'bool',   'startYear':'int64',    'endYear':'int64',  'runtimeMinutes':'int64',   'genres':'str'})


countries = cwd+'/datasets/countries.list.gz'
countries_table = get_movie_countries(countries)
countries_table.to_csv("countries_table.csv")

movies = cwd+'/datasets/movie-links.list.gz'
movies_table = get_movie_links(movies)

'''
testing the tables
'''
# print(movies_table.head(5))
# print(countries_table.head(5))
# print(title_table.head(5))
# print(name_table.head(5))


#merge to include countries:

movies_cit_countries = pd.merge(movies_table, countries_table, on='movie', how='left')

movies_cit_countries=pd.merge(movies_cit_countries, countries_table, left_on="cites", right_on="movie",how="left")

movies_cit_countries.rename(columns={"movie_x":"movie","movie_y":"cited_movies","country_x":"movie_country","country_y":"cites_country"},inplace=True)
movies_cit_countries=movies_cit_countries.reindex(columns= ['movie', 'movie_country', 'cites', 'movie_y','cites_country'])
movies_cit_countries.drop(columns=['movie_y'], inplace=True)
movies_cit_countries.head(30)

# str(len(movies_cit_countries)) + " final, original is " + str(len(movies_table))

#the lengths are different and i don't understand why
#retrieve information for movies collaborators. **not currently working**

#how to match

#append the movie title to the tconst ones.
#split the movie column in the first dataframe to separate title from year
#match both movie title (that is ***included*** in the imdb, so not an exact match) and year with startYear

#

movies_cit_countries[['title','year']] = movies_cit_countries.movie.str.split("\(", 1, expand=True)
movies_cit_countries['year']=movies_cit_countries['year'].str.replace(')','')

movies_cit_countries[['primaryTitle_citation','year_citation']] = movies_cit_countries.cites.str.split("\(", 1, expand=True)
movies_cit_countries['year_citation']=movies_cit_countries['year_citation'].str.replace(')','')

movies_cit_countries[:100]
#final_df = title_name_table.merge(movies_cit_countries, how="inner", left_on= "primaryTitle" , right_on= "title_citation")
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)
# final_df[:50]

# Convert all columns in movies_cit_countries to strings
# movies_cit_countries = movies_cit_countries.astype(str)

# # Convert all columns in title_name_table to strings
# title_name_table = title_name_table.astype(str)

#encoding is same in both, utf-8.

# import chardet as chardet

# # Convert dataframes to strings
# movies_cit_countries_str = movies_cit_countries.to_csv(index=False).encode()
# title_name_table_str = title_name_table.to_csv(index=False).encode()

# # Check encoding for movies_cit_countries
# movies_cit_countries_encoding = chardet.detect(movies_cit_countries_str)['encoding']
# print('Encoding for movies_cit_countries:', movies_cit_countries_encoding)

# # Check encoding for title_name_table
# title_name_table_encoding = chardet.detect(title_name_table_str)['encoding']
# print('Encoding for title_name_table:', title_name_table_encoding)
#assign best datatypes = they all turn out as str

movies_cit_countries=movies_cit_countries.convert_dtypes()
title_name_table=title_name_table.convert_dtypes()

#remove trailing whitespaces
title_name_table['primaryTitle'] = title_name_table['primaryTitle'].str.strip()
title_name_table['originalTitle'] = title_name_table['originalTitle'].str.strip()

title_name_table['primaryTitle'] = title_name_table['primaryTitle'].str.strip()
title_name_table['originalTitle'] = title_name_table['originalTitle'].str.strip()
 # Check for leading/trailing whitespaces in string columns in movies_cit_countries
string_columns = ['movie_country', 'cites_country','year_citation']
for column in string_columns:
    mask = movies_cit_countries[column].str.strip() != movies_cit_countries[column]
    if mask.any():
        print(f"{column} has leading/trailing whitespaces")
    else:
        print(f"{column} clear")

# Check for leading/trailing whitespaces in string columns in title_name_table
string_columns = ['primaryTitle', 'originalTitle', 'genres','startYear']
for column in string_columns:
    mask = title_name_table[column].str.strip() != title_name_table[column]
    if mask.any():
        print(f"{column} has leading/trailing whitespaces")

    else:
        print(f"{column} clear")


# Check for duplicate values in column "primaryTitle_citation" in movies_cit_countries
if movies_cit_countries['primaryTitle_citation'].duplicated().any():
    print("primaryTitle_citation column in movies_cit_countries has duplicate values")

# Check for duplicate values in column "primaryTitle" in title_name_table
if title_name_table['primaryTitle'].duplicated().any():
    print("primaryTitle column in title_name_table has duplicate values")




# merged_df = pd.merge(movies_cit_countries, title_name_table,
#                      how='left',
#                      left_on='primaryTitle_citation',
#                      right_on='primaryTitle')
final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


final_df




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how='left',
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df

merged_df.info()




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how='left',
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df
 # Check for leading/trailing whitespaces in string columns in movies_cit_countries
string_columns = ['movie_country', 'cites_country','year_citation']
for column in string_columns:
    mask = movies_cit_countries[column].str.strip() != movies_cit_countries[column]
    if mask.any():
        print(f"{column} has leading/trailing whitespaces")
    else:
        print(f"{column} clear")

# Check for leading/trailing whitespaces in string columns in title_name_table
string_columns = ['primaryTitle', 'originalTitle', 'genres','startYear']
for column in string_columns:
    mask = title_name_table[column].str.strip() != title_name_table[column]
    if mask.any():
        print(f"{column} has leading/trailing whitespaces")

    else:
        print(f"{column} clear")


# Check for duplicate values in column "primaryTitle_citation" in movies_cit_countries
if movies_cit_countries['primaryTitle_citation'].duplicated().any():
    print("primaryTitle_citation column in movies_cit_countries has duplicate values")

# Check for duplicate values in column "primaryTitle" in title_name_table
if title_name_table['primaryTitle'].duplicated().any():
    print("primaryTitle column in title_name_table has duplicate values")
'''

CINEMAC.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

project for the course of Network Analysis - 2022/2023
Realized by.
    Andrea D'Arpa
    Maddalena Ghiotto
    Chloe Papadopoulou

'''
import os
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from ast import literal_eval
from listReader import *
!pip install chardet


# creating the tables with pandas to interact with our datasets
# getting the current working directory
cwd = os.getcwd()

name = cwd+'/datasets/name.basics.tsv'
name_table = pd.read_csv(name , sep='\t', header=0)

title = cwd+'/datasets/title.principals.tsv'
title_table = pd.read_csv(title , sep='\t', header=0)

#import titles ds to match the movie-links titles,
title_name = cwd+'/datasets/title.basics.tsv'
title_name_table= pd.read_csv(title_name, sep='\t', header=0, low_memory=False)


# dtype={'tconst':'int64',  'titleType':'str',  'primaryTitle':'str',   'originalTitle':'str',  'isAdult':'bool',   'startYear':'int64',    'endYear':'int64',  'runtimeMinutes':'int64',   'genres':'str'})


countries = cwd+'/datasets/countries.list.gz'
countries_table = get_movie_countries(countries)
countries_table.to_csv("countries_table.csv")

movies = cwd+'/datasets/movie-links.list.gz'
movies_table = get_movie_links(movies)

'''
testing the tables
'''
# print(movies_table.head(5))
# print(countries_table.head(5))
# print(title_table.head(5))
# print(name_table.head(5))


#merge to include countries:

movies_cit_countries = pd.merge(movies_table, countries_table, on='movie', how='left')

movies_cit_countries=pd.merge(movies_cit_countries, countries_table, left_on="cites", right_on="movie",how="left")

movies_cit_countries.rename(columns={"movie_x":"movie","movie_y":"cited_movies","country_x":"movie_country","country_y":"cites_country"},inplace=True)
movies_cit_countries=movies_cit_countries.reindex(columns= ['movie', 'movie_country', 'cites', 'movie_y','cites_country'])
movies_cit_countries.drop(columns=['movie_y'], inplace=True)
movies_cit_countries.head(30)

# str(len(movies_cit_countries)) + " final, original is " + str(len(movies_table))

#the lengths are different and i don't understand why
#retrieve information for movies collaborators. **not currently working**

#how to match

#append the movie title to the tconst ones.
#split the movie column in the first dataframe to separate title from year
#match both movie title (that is ***included*** in the imdb, so not an exact match) and year with startYear

#replace n for nan values

title_name_table = title_name_table.replace("\\N", np.nan)


movies_cit_countries[['title','year']] = movies_cit_countries.movie.str.split("\(", 1, expand=True)
movies_cit_countries['year']=movies_cit_countries['year'].str.replace(')','')

movies_cit_countries[['primaryTitle_citation','year_citation']] = movies_cit_countries.cites.str.split("\(", 1, expand=True)
movies_cit_countries['year_citation']=movies_cit_countries['year_citation'].str.replace(')','')
#final_df = title_name_table.merge(movies_cit_countries, how="inner", left_on= "primaryTitle" , right_on= "title_citation")
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)
# final_df[:50]

# Convert all columns in movies_cit_countries to strings
# movies_cit_countries = movies_cit_countries.astype(str)

# # Convert all columns in title_name_table to strings
# title_name_table = title_name_table.astype(str)

#encoding is same in both, utf-8.

# import chardet as chardet

# # Convert dataframes to strings
# movies_cit_countries_str = movies_cit_countries.to_csv(index=False).encode()
# title_name_table_str = title_name_table.to_csv(index=False).encode()

# # Check encoding for movies_cit_countries
# movies_cit_countries_encoding = chardet.detect(movies_cit_countries_str)['encoding']
# print('Encoding for movies_cit_countries:', movies_cit_countries_encoding)

# # Check encoding for title_name_table
# title_name_table_encoding = chardet.detect(title_name_table_str)['encoding']
# print('Encoding for title_name_table:', title_name_table_encoding)
#assign best datatypes = they all turn out as str


movies_cit_countries=movies_cit_countries.convert_dtypes()
title_name_table=title_name_table.convert_dtypes()

#remove trailing whitespaces
title_name_table['primaryTitle'] = title_name_table['primaryTitle'].str.strip()
title_name_table['originalTitle'] = title_name_table['originalTitle'].str.strip()

title_name_table['primaryTitle'] = title_name_table['primaryTitle'].str.strip()
title_name_table['originalTitle'] = title_name_table['originalTitle'].str.strip()
 # Check for leading/trailing whitespaces in string columns in movies_cit_countries
string_columns = ['movie_country', 'cites_country','year_citation']
for column in string_columns:
    mask = movies_cit_countries[column].str.strip() != movies_cit_countries[column]
    if mask.any():
        print(f"{column} has leading/trailing whitespaces")
    else:
        print(f"{column} clear")

# Check for leading/trailing whitespaces in string columns in title_name_table
string_columns = ['primaryTitle', 'originalTitle', 'genres','startYear']
for column in string_columns:
    mask = title_name_table[column].str.strip() != title_name_table[column]
    if mask.any():
        print(f"{column} has leading/trailing whitespaces")

    else:
        print(f"{column} clear")


# Check for duplicate values in column "primaryTitle_citation" in movies_cit_countries
if movies_cit_countries['primaryTitle_citation'].duplicated().any():
    print("primaryTitle_citation column in movies_cit_countries has duplicate values")

# Check for duplicate values in column "primaryTitle" in title_name_table
if title_name_table['primaryTitle'].duplicated().any():
    print("primaryTitle column in title_name_table has duplicate values")
movies_cit_countries[:100]
title_name_table[:100]




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how='left',
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="outer",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="left",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="right",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="right",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


# merged_df

merged_df[['primaryTitle'] == 'Fight Club'].values




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="right",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


# merged_df

merged_df[merged_df['primaryTitle'] == 'Fight Club'].values
movies_cit_countries[:100]
title_name_table[:100]
title_name_table = title_name_table[title_name_table['titleType'] == 'movie']

title_name_table[title_name_table['primaryTitle'] == 'Fight Club'].values




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="right",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


# merged_df

merged_df[merged_df['primaryTitle'] == 'Fight Club'].values




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="left",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df

# merged_df[merged_df['primaryTitle'] == 'Fight Club'].values




merged_df = pd.merge(movies_cit_countries, title_name_table,
                     how="outer",
                     left_on='primaryTitle_citation',
                     right_on='primaryTitle')
# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='inner', lsuffix='', rsuffix='_citation', sort=False)



# # title_name_table.info()
# # movies_cit_countries.info()


merged_df

# merged_df[merged_df['primaryTitle'] == 'Fight Club'].values



