In [2]:
'''

CINEMAC. 

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

project for the course of Network Analysis - 2022/2023
Realized by.
	Andrea D'Arpa
	Maddalena Ghiotto		
	Chloe Papadopoulou

'''
import os
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from ast import literal_eval
from listReader import *


# creating the tables with pandas to interact with our datasets
# getting the current working directory
cwd = os.getcwd()

name = cwd+'/datasets/name.basics.tsv'
name_table = pd.read_csv(name , sep='\t', header=0)

title = cwd+'/datasets/title.principals.tsv'
title_table = pd.read_csv(title , sep='\t', header=0)

#import titles ds to match the movie-links titles, 
title_name = cwd+'/datasets/title.basics.tsv'
title_name_table= pd.read_csv(title_name, sep='\t', header=0, low_memory=False)

                              
# # dtype={'tconst':'int64',	'titleType':'str',	'primaryTitle':'str',	'originalTitle':'str',	'isAdult':'bool',	'startYear':'int64',	'endYear':'int64',	'runtimeMinutes':'int64',	'genres':'str'})


countries = cwd+'/datasets/countries.list.gz'
countries_table = get_movie_countries(countries)
countries_table.to_csv("countries_table.csv")

movies = cwd+'/datasets/movie-links.list.gz'
movies_table = get_movie_links(movies)
movies_table.to_csv("movies_table.csv")

'''
testing the tables
'''
# print(movies_table.head(5))
# print(countries_table.head(5))
# print(title_table.head(5))
# print(name_table.head(5))


#merge to include countries:

movies_cit_countries = pd.merge(movies_table, countries_table, on='movie', how='left')

movies_cit_countries=pd.merge(movies_cit_countries, countries_table, left_on="cites", right_on="movie",how="left")

movies_cit_countries.rename(columns={"movie_x":"movie","movie_y":"cited_movies","country_x":"movie_country","country_y":"cites_country"},inplace=True)
movies_cit_countries=movies_cit_countries.reindex(columns= ['movie', 'movie_country', 'cites', 'movie_y','cites_country'])
movies_cit_countries.drop(columns=['movie_y'], inplace=True)
movies_cit_countries.head(30)

,movie,movie_country,cites,cites_country
0,#DevinAuditions (2016),Canada,Alien (1979),UK
1,#DevinAuditions (2016),Canada,Alien (1979),USA
2,#DevinAuditions (2016),Canada,Die Hard (1988),USA
3,#DevinAuditions (2016),Canada,Ferris Bueller's Day Off (1986),USA
4,#DevinAuditions (2016),Canada,Fight Club (1999),USA
5,#DevinAuditions (2016),Canada,Fight Club (1999),Germany
6,#DevinAuditions (2016),Canada,Magic Mike (2012),USA
7,#DevinAuditions (2016),Canada,The Gold Rush (1925),USA
8,#DevinAuditions (2016),Canada,The Shining (1980),UK
9,#DevinAuditions (2016),Canada,The Shining (1980),USA
10,#FromJennifer (2017),USA,2 Jennifer (2016),USA
11,#FromJennifer (2017),USA,To Jennifer (2013),USA
12,#Rip (2013),USA,"Love, Simple (2012)",USA
13,#TubeClash02 (2016),Germany,Star Wars (1977),USA
14,#chicagoGirl: The Social Network Takes on a Di...,USA,The Godfather (1972),USA
15,#chicagoGirl: The Social Network Takes on a Di...,Syria,The Godfather (1972),USA
16,#twitterkills (2014),USA,Frankenstein (1910),USA
17,#will (2016),Sweden,Life of Brian (1979),UK
18,#will (2016),Sweden,The Silence of the Lambs (1991),USA
19,$10 Raise (1935),USA,The Ten Dollar Raise (1921),USA
20,"$10,000 Under a Pillow (1921)",USA,Bud Takes the Cake (1920),USA
21,"$10,000 Under a Pillow (1921)",USA,Bud and Susie Join the Tecs (1920),USA
22,"$10,000 Under a Pillow (1921)",USA,Bud and Tommy Take a Day Off (1920),USA
23,"$10,000 Under a Pillow (1921)",USA,By the Sea (1921),USA
24,"$10,000 Under a Pillow (1921)",USA,Circumstantial Evidence (1921),USA
25,"$10,000 Under a Pillow (1921)",USA,Down the Mississippi (1920),USA
26,"$10,000 Under a Pillow (1921)",USA,Fifty-Fifty (1920),USA
27,"$10,000 Under a Pillow (1921)",USA,Getting Theirs (1921),USA
28,"$10,000 Under a Pillow (1921)",USA,Handy Mandy's Goat (1920),USA
29,"$10,000 Under a Pillow (1921)",USA,Ma's Wipe Your Feet Campaign (1921),USA

In [3]:
#retrieve information for movies collaborators

#split the movie column in the first dataframe to separate title from year

#replace /n for nan values
title_name_table = title_name_table.replace("\\N", np.nan)


# movies_cit_countries[['title','year']] = movies_cit_countries.movie.str.split("\(", 1, expand=True)
# movies_cit_countries['year']=movies_cit_countries['year'].str.replace(')','')  

# movies_cit_countries[['primaryTitle_citation','year_citation']] = movies_cit_countries.cites.str.split("\(", 1, expand=True)
# movies_cit_countries['year_citation']=movies_cit_countries['year_citation'].str.replace(')','')  


# pattern of four digits between parentheses at the end of the string
pattern = r'^(.*) \((\d{4})\)$'

movies_cit_countries[['title', 'year']] = movies_cit_countries['movie'].str.extract(pattern)
movies_cit_countries[['primaryTitle_citation', 'year_citation']] = movies_cit_countries['cites'].str.extract(pattern)

# Print the first 10 rows of the resulting dataframe to check the output
print(movies_cit_countries.head(100))

                                     movie movie_country  \
0                   #DevinAuditions (2016)        Canada
1                   #DevinAuditions (2016)        Canada
2                   #DevinAuditions (2016)        Canada
3                   #DevinAuditions (2016)        Canada
4                   #DevinAuditions (2016)        Canada
..                                     ...           ...
95          'Joe Strummer': The Man (2007)           USA
96    'Kurenai no kenjû' yo eien ni (2000)         Japan
97  'Men Olsenbanden var ikke død!' (1984)        Norway
98  'Men Olsenbanden var ikke død!' (1984)        Norway
99  'Men Olsenbanden var ikke død!' (1984)        Norway

                                             cites cites_country  \
0                                     Alien (1979)            UK
1                                     Alien (1979)           USA
2                                  Die Hard (1988)           USA
3                  Ferris Bueller's Day Off (1986)           USA
4                                Fight Club (1999)           USA
..                                             ...           ...
95    Joe Strummer: The Future Is Unwritten (2007)            UK
96                         Kurenai no kenju (1961)         Japan
97     Olsen-banden møter kongen og knekten (1974)        Norway
98           Olsen-banden og Dynamitt-Harry (1970)        Norway
99  Olsen-banden og Dynamitt-Harry går amok (1973)        Norway

                              title  year  \
0                   #DevinAuditions  2016
1                   #DevinAuditions  2016
2                   #DevinAuditions  2016
3                   #DevinAuditions  2016
4                   #DevinAuditions  2016
..                              ...   ...
95          'Joe Strummer': The Man  2007
96    'Kurenai no kenjû' yo eien ni  2000
97  'Men Olsenbanden var ikke død!'  1984
98  'Men Olsenbanden var ikke død!'  1984
99  'Men Olsenbanden var ikke død!'  1984

                      primaryTitle_citation year_citation
0                                     Alien          1979
1                                     Alien          1979
2                                  Die Hard          1988
3                  Ferris Bueller's Day Off          1986
4                                Fight Club          1999
..                                      ...           ...
95    Joe Strummer: The Future Is Unwritten          2007
96                         Kurenai no kenju          1961
97     Olsen-banden møter kongen og knekten          1974
98           Olsen-banden og Dynamitt-Harry          1970
99  Olsen-banden og Dynamitt-Harry går amok          1973

[100 rows x 8 columns]

In [4]:
#******TROUBLESHOOTING missing values on merge ********

#encoding is same in both, utf-8 - check
#replaced /n for nan values before

In [5]:
#make sure formats are the same
#assign best datatypes

movies_cit_countries=movies_cit_countries.convert_dtypes()
title_name_table=title_name_table.convert_dtypes()

#they all turn out as str- keeping it for convenience

#remove useless whitespaces
movies_cit_countries['title'] = movies_cit_countries['title'].str.strip()
movies_cit_countries['primaryTitle_citation'] = movies_cit_countries['primaryTitle_citation'].str.strip()

title_name_table['primaryTitle'] = title_name_table['primaryTitle'].str.strip()
title_name_table['originalTitle'] = title_name_table['originalTitle'].str.strip()

In [22]:
#check duplicates
# movies_cit_countries['primaryTitle_citation'].duplicated().any()

# title_name_table['primaryTitle'].duplicated().any()


final_df = pd.merge(movies_cit_countries, title_name_table,
             how="left",
             left_on=['primaryTitle_citation', 'year_citation'],
             right_on=['originalTitle', 'startYear'])

# final_df = title_name_table.set_index('primaryTitle').join(movies_cit_countries, how='right', lsuffix='', rsuffix='_citation', sort=False)

                                

final_df

,movie,movie_country,cites,cites_country,title,year,primaryTitle_citation,year_citation,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,#DevinAuditions (2016),Canada,Alien (1979),UK,#DevinAuditions,2016,Alien,1979,tt0078748,movie,Alien,Alien,0,1979,<NA>,117,"Horror,Sci-Fi"
1,#DevinAuditions (2016),Canada,Alien (1979),USA,#DevinAuditions,2016,Alien,1979,tt0078748,movie,Alien,Alien,0,1979,<NA>,117,"Horror,Sci-Fi"
2,#DevinAuditions (2016),Canada,Die Hard (1988),USA,#DevinAuditions,2016,Die Hard,1988,tt0095016,movie,Die Hard,Die Hard,0,1988,<NA>,132,"Action,Thriller"
3,#DevinAuditions (2016),Canada,Ferris Bueller's Day Off (1986),USA,#DevinAuditions,2016,Ferris Bueller's Day Off,1986,tt0091042,movie,Ferris Bueller's Day Off,Ferris Bueller's Day Off,0,1986,<NA>,103,Comedy
4,#DevinAuditions (2016),Canada,Fight Club (1999),USA,#DevinAuditions,2016,Fight Club,1999,tt0137523,movie,Fight Club,Fight Club,0,1999,<NA>,139,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402033,è solo questione di punti di vista (2012),Italy,"Un genio, due compari, un pollo (1975)",West Germany,è solo questione di punti di vista,2012,"Un genio, due compari, un pollo",1975,tt0073036,movie,"A Genius, Two Partners and a Dupe","Un genio, due compari, un pollo",0,1975,<NA>,126,"Comedy,Western"
402034,è solo questione di tempo (2013),Italy,Il successo (1963),Italy,è solo questione di tempo,2013,Il successo,1963,tt0057540,movie,Il successo,Il successo,0,1963,<NA>,104,Comedy
402035,è solo questione di tempo (2013),Italy,Il successo (1963),Italy,è solo questione di tempo,2013,Il successo,1963,tt1248945,tvMovie,Il successo,Il successo,0,1963,<NA>,90,<NA>
402036,è solo questione di tempo (2013),Italy,Il successo (1963),France,è solo questione di tempo,2013,Il successo,1963,tt0057540,movie,Il successo,Il successo,0,1963,<NA>,104,Comedy
402037,è solo questione di tempo (2013),Italy,Il successo (1963),France,è solo questione di tempo,2013,Il successo,1963,tt1248945,tvMovie,Il successo,Il successo,0,1963,<NA>,90,<NA>

In [7]:
# testing
# repo_data_ex= movies_cit_countries[movies_cit_countries['primaryTitle_citation'] == 'Fight Club'].values
# repo_data_ex

In [23]:

non_valid_year = list([y for y in movies_cit_countries['year'].unique() if not (str(y).isdigit() and len(str(y)) == 4)])
non_valid_year
error_rows = movies_cit_countries[movies_cit_countries['year'].isin(non_valid_year)]
error_rows

non_valid_year_x = list([y for y in movies_cit_countries['year_citation'].unique() if not (str(y).isdigit() and len(str(y)) == 4)])
non_valid_year_x
error_rows_x = movies_cit_countries[movies_cit_countries['year_citation'].isin(non_valid_year_x)]
error_rows.empty and error_rows_x.empty

True

In [24]:
final_df.drop_duplicates(subset=["originalTitle","startYear","primaryTitle_citation", "year_citation"], inplace=True)

final_df.isnull().sum()

movie                        0
movie_country               57
cites                        0
cites_country               39
title                        0
year                         0
primaryTitle_citation        0
year_citation                0
tconst                    1915
titleType                 1915
primaryTitle              1915
originalTitle             1915
isAdult                   1915
startYear                 1915
endYear                  42998
runtimeMinutes            6313
genres                    2717
dtype: int64

In [25]:
null_values = final_df['originalTitle'].isnull() | final_df['originalTitle'].isna()

#show non matched data
final_df[null_values]

#to check:

,movie,movie_country,cites,cites_country,title,year,primaryTitle_citation,year_citation,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
152,'Merci la vie' (1991),France,Buffet froid (1979),France,'Merci la vie',1991,Buffet froid,1979,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
301,(500) Days of Summer (2009),USA,Littleman (2006),USA,(500) Days of Summer,2009,Littleman,2006,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
366,(500) Days of Summer (2009),USA,Three Seasons (1999),Vietnam,(500) Days of Summer,2009,Three Seasons,1999,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
412,(T)Raumschiff Surprise - Periode 1 (2004),Germany,Le cinquième élément (1997),France,(T)Raumschiff Surprise - Periode 1,2004,Le cinquième élément,1997,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
421,(T)Raumschiff Surprise - Periode 1 (2004),Germany,Star Wars: Episode V - The Empire Strikes Back...,USA,(T)Raumschiff Surprise - Periode 1,2004,Star Wars: Episode V - The Empire Strikes Back,1980,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401152,Zülfü Livaneli: A Voice Between East and West ...,Germany,Yer demir gök bakir (1987),Turkey,Zülfü Livaneli: A Voice Between East and West,2014,Yer demir gök bakir,1987,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
401489,À bout de souffle (1960),France,Westbound (1959),USA,À bout de souffle,1960,Westbound,1959,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
401866,Çilgin dersane 3 (2014),Turkey,Çilgin dersane kampta (2008),Turkey,Çilgin dersane 3,2014,Çilgin dersane kampta,2008,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
401910,Éden (2011),Portugal,Thunder in the East (1951),USA,Éden,2011,Thunder in the East,1951,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
402004,Üç arkadas (1971),Turkey,Üç arkadas (1958),Turkey,Üç arkadas,1971,Üç arkadas,1958,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>